export const cards = [
    { id: 1, rank: 2, type: 'bubi', img: '2B.png' },
    { id: 2, rank: 2, type: 'chervi', img: '2CH.png' },
    { id: 3, rank: 2, type: 'kresti', img: '2K.png' },
    { id: 4, rank: 2, type: 'piki', img: '2P.png' },
    { id: 5, rank: 3, type: 'bubi', img: '3B.png' },
    { id: 6, rank: 3, type: 'chervi', img: '3CH.png' },
    { id: 7, rank: 3, type: 'kresti', img: '3K.png' },
    { id: 8, rank: 3, type: 'piki', img: '3P.png' },
    { id: 9, rank: 4, type: 'bubi', img: '4B.png' },
    { id: 10, rank: 4, type: 'chervi', img: '4CH.png' },
    { id: 11, rank: 4, type: 'kresti', img: '4K.png' },
    { id: 12, rank: 4, type: 'piki', img: '4P.png' },
    { id: 13, rank: 5, type: 'bubi', img: '5B.png' },
    { id: 14, rank: 5, type: 'chervi', img: '5CH.png' },
    { id: 15, rank: 5, type: 'kresti', img: '5K.png' },
    { id: 16, rank: 5, type: 'piki', img: '5P.png' },
    { id: 17, rank: 6, type: 'bubi', img: '6B.png' },
    { id: 18, rank: 6, type: 'chervi', img: '6CH.png' },
    { id: 19, rank: 6, type: 'kresti', img: '6K.png' },
    { id: 20, rank: 6, type: 'piki', img: '6P.png' },
    { id: 21, rank: 7, type: 'bubi', img: '7B.png' },
    { id: 22, rank: 7, type: 'chervi', img: '7CH.png' },
    { id: 23, rank: 7, type: 'kresti', img: '7K.png' },
    { id: 24, rank: 7, type: 'piki', img: '7P.png' },
    { id: 25, rank: 8, type: 'bubi', img: '8B.png' },
    { id: 26, rank: 8, type: 'chervi', img: '8CH.png' },
    { id: 27, rank: 8, type: 'kresti', img: '8K.png' },
    { id: 28, rank: 8, type: 'piki', img: '8P.png' },
    { id: 29, rank: 9, type: 'bubi', img: '9B.png' },
    { id: 30, rank: 9, type: 'chervi', img: '9CH.png' },
    { id: 31, rank: 9, type: 'kresti', img: '9K.png' },
    { id: 32, rank: 9, type: 'piki', img: '9P.png' },
    { id: 33, rank: 10, type: 'bubi', img: '10B.png' },
    { id: 34, rank: 10, type: 'chervi', img: '10CH.png' },
    { id: 35, rank: 10, type: 'kresti', img: '10K.png' },
    { id: 36, rank: 10, type: 'piki', img: '10P.png' },
    { id: 37, rank: 11, type: 'bubi', img: 'VB.png' },
    { id: 38, rank: 11, type: 'chervi', img: 'VCH.png' },
    { id: 39, rank: 11, type: 'kresti', img: 'VK.png' },
    { id: 40, rank: 11, type: 'piki', img: 'VP.png' },
    { id: 41, rank: 12, type: 'bubi', img: 'DB.png' },
    { id: 42, rank: 12, type: 'chervi', img: 'DCH.png' },
    { id: 43, rank: 12, type: 'kresti', img: 'DK.png' },
    { id: 44, rank: 12, type: 'piki', img: 'DP.png' },
    { id: 45, rank: 13, type: 'bubi', img: 'KB.png' },
    { id: 46, rank: 13, type: 'chervi', img: 'KCH.png' },
    { id: 47, rank: 13, type: 'kresti', img: 'KK.png' },
    { id: 48, rank: 13, type: 'piki', img: 'KP.png' },
    { id: 49, rank: 14, type: 'bubi', img: 'TB.png' },
    { id: 50, rank: 14, type: 'chervi', img: 'TCH.png' },
    { id: 51, rank: 14, type: 'kresti', img: 'TK.png' },
    { id: 52, rank: 14, type: 'piki', img: 'TP.png' },
    // { id: 53, rank: 14, type: 'piki', img: 'DCH2.png' },
];

export const trumps = [
    {type: 'chervi', img: 'ch.png'},
    {type: 'kresti', img: 'kresti.png'},
    {type: 'bubi', img: 'bubi.png'},
    {type: 'piki', img: 'piki.png'},

]